it_solution/urls.py
from django.urls import path

from it_solution import views

app_name = 'it_solution'

urlpatterns = [
    path("", views.homeview, name="home"),
    path("about/", views.aboutview, name="about"),
    path("services/", views.servicesview, name="services"),
    path("project/", views.projectview, name="project"),
    path("news/", views.newsview, name="news"),
    path("contact/", views.contactview, name="contact"),
    path("comments/", views.commentview, name="comments"),
    path("cloud-computing/", views.cloudcomputing, name="cloudcomputing"),
    path("it-consultancy/", views.itconsultancy, name="it-consultancy"),
    path("custom-software/", views.customsoftware, name="custom-software"),
    path("news/<int:pk>/", views.newsdetailsview, name="news-details"),
    path("project/<int:pk>/", views.projectdetailsview, name="project-details"),






    path("admin-page/", views.adminview, name= "admin-page"),
    path("addnews/", views.addnewsview, name="addnews"),
    path("newslist/", views.newslistview, name= "newslist"),
    path("addproject/", views.addprojectview, name= "addproject"),
    path("projectlist/", views.projectlistview, name= "projectlist"),

 
    path("editproject/<int:project_id>/", views.editprojectview, name= "editproject"),
    path('delete/<int:project_id>/', views.delete_project, name='delete_project'),
    
    path("editnews/<int:news_id>", views.editnewsview, name= "editnews"),
    path('delete/news/<int:news_id>/', views.delete_news, name='delete_news'),
  
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("it_solution.urls")),
    path("",include("nirajan.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nirajan/urls.py
from django.urls import path

from nirajan import views

app_name = 'nirajan'

urlpatterns = [

    # path('admin_signup/', views.admin_login_view, name='signup'),
    path('login/admin_login/', views.login_view, name='admin_login'),
    path('admin/dashboard/', views.dashboard_view, name='dashboard'),
    path('logout/',views.logout_view, name="logout")
]

templates/news.html
{% extends "base.html" %}

{% load custom_filters %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>News || Izeetak || Izeetak HTML Template For IT Solutions Company</title>
    <!-- favicons Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/favicons/apple-touch-icon.png' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/favicons/favicon-32x32.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicons/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% static 'assets/images/favicons/site.webmanifest' %}" />
    <meta name="description" content="Izeetak HTML Template For IT Solutions Company" />

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">


    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/animate/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/animate/custom-animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/fontawesome/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jarallax/jarallax.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.pips.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/odometer/odometer.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/swiper/swiper.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/izeetak-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/tiny-slider/tiny-slider.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/reey-font/stylesheet.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/twentytwenty/twentytwenty.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/bxslider/jquery.bxslider.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap-select/css/bootstrap-select.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/vegas/vegas.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jquery-ui/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/timepicker/timePicker.css' %}" />

    <!-- template styles -->
    <link rel="stylesheet" href="{% static 'assets/css/izeetak.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/izeetak-responsive.css' %}" />
</head>

<body>
    <div class="preloader">
        <img class="preloader__image" width="60" src="{% static 'assets/images/loader.png' %}" alt="" />
    </div>
    <!-- /.preloader -->
    <div class="page-wrapper">
        <header class="main-header clearfix">
            <div class="main-header__top clearfix">
                <div class="main-header__top-inner clearfix">
                    <div class="main-header__top-left">
                        <ul class="list-unstyled main-header__top-address">
                            <li>
                                <div class="icon">
                                    <span class="icon-pin"></span>
                                </div>
                                <div class="text">
                                    <p>66 Road Broklyn Golden Street. New York</p>
                                </div>
                            </li>
                            <li>
                                <div class="icon">
                                    <span class="icon-email"></span>
                                </div>
                                <div class="text">
                                    <p><a href="mailto:needhelp@company.com">needhelp@company.com</a></p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="main-header__top-right">
                        <div class="main-header__top-right-text">
                            <p><span>Now Hiring:</span> Are you a driven and motivated 1st Line IT Support Engineer?</p>
                        </div>
                        <div class="main-header__top-right-social">
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-facebook"></i></a>
                            <a href="#"><i class="fab fa-pinterest-p"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
        </header>

        <div class="stricky-header stricked-menu main-menu">
            <div class="sticky-header__content"></div><!-- /.sticky-header__content -->
        </div><!-- /.stricky-header -->

        <!--Page Header Start-->
        <section class="page-header">
            <div class="page-header-bg" style="background-image: url({% static 'assets/images/backgrounds/a5.jpg' %})">
            </div>
            <div class="page-header-bg-overly"></div>
            <div class="page-header-shape wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
                style="background-image: url({% static 'assets/images/shapes/page-header-shape.png' %})"></div>
            <div class="container">
                <div class="page-header__inner">
                    <ul class="thm-breadcrumb list-unstyled">
                        <li><a href="{% url 'it_solution:home' %}">Home</a></li>
                        <li><span>/</span></li>
                        <li>News</li>
                    </ul>
                    <h2>Latest News</h2>
                </div>
            </div>
        </section>
        <!--Page Header End-->

        <!--News Page Start-->
        <section class="news-one news-page">
            <div class="container">
                <div class="row">
                    {% for news in latest_news %}
                    <div class="col-xl-4 col-lg-4 wow fadeInLeft" data-wow-delay="100ms">
                        <!--News One Single-->
                        <div class="news-one__single">
                            <div class="news-one__img">
                                <img src="{{ news.image.url }}" alt="">
                                <a href="{% url 'it_solution:news-details' news.id %}">
                                    <span class="news-one__plus"></span>
                                </a>
                                <div class="news-one__date-box">
                                    <p>{{ news.date }}</p>
                                </div>
                            </div>
                            <div class="news-one__content">
                                <ul class="list-unstyled news-one__meta">
                                    <li><a href="#"><i class="far fa-user-circle"></i> by{{ news.admin }}</a></li>
                                    <li><a href="#"><i class="far fa-comments"></i> {{ news.comments }}</a>
                                    </li>
                                </ul>
                                <h3 class="news-one__title">
                                    <a href="{% url 'it_solution:news-details' news.id %}">{{ news.title }}</a>
                                </h3>
                                <p class="news-one__text"> {{ news.content|richtext_truncatewords:10 }}
                                </p>
                                <div class="news-one__read-more">
                                    <a href="{% url 'it_solution:news-details' news.id %}" class="news-one__read-more-btn">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
                    
                     
                    </div><!-- /.col-xl-12 -->
                </div>
            </div>
        </section>
        <!--News Page End-->

  


    </div><!-- /.page-wrapper -->


    <div class="mobile-nav__wrapper">
        <div class="mobile-nav__overlay mobile-nav__toggler"></div>
        <!-- /.mobile-nav__overlay -->
        <div class="mobile-nav__content">
            <span class="mobile-nav__close mobile-nav__toggler"><i class="fa fa-times"></i></span>

            <div class="logo-box">
                <a href="index.html" aria-label="logo image"><img src="{% static 'assets/images/resources/footer-logo.png' %}"
                        width="155" alt="" /></a>
            </div>
            <!-- /.logo-box -->
            <div class="mobile-nav__container"></div>
            <!-- /.mobile-nav__container -->

            <ul class="mobile-nav__contact list-unstyled">
                <li>
                    <i class="fa fa-envelope"></i>
                    <a href="mailto:needhelp@packageName__.com">needhelp@izeetak.com</a>
                </li>
                <li>
                    <i class="fa fa-phone-alt"></i>
                    <a href="tel:666-888-0000">666 888 0000</a>
                </li>
            </ul><!-- /.mobile-nav__contact -->
            <div class="mobile-nav__top">
                <div class="mobile-nav__social">
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-facebook-square"></a>
                    <a href="#" class="fab fa-pinterest-p"></a>
                    <a href="#" class="fab fa-instagram"></a>
                </div><!-- /.mobile-nav__social -->
            </div><!-- /.mobile-nav__top -->



        </div>
        <!-- /.mobile-nav__content -->
    </div>
    <!-- /.mobile-nav__wrapper -->

    <div class="search-popup">
        <div class="search-popup__overlay search-toggler"></div>
        <!-- /.search-popup__overlay -->
        <div class="search-popup__content">
            <form action="#">
                <label for="search" class="sr-only">search here</label><!-- /.sr-only -->
                <input type="text" id="search" placeholder="Search Here..." />
                <button type="submit" aria-label="search submit" class="thm-btn">
                    <i class="icon-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <!-- /.search-popup__content -->
    </div>
    <!-- /.search-popup -->

    <a href="#" data-target="html" class="scroll-to-target scroll-to-top"><i class="fa fa-angle-up"></i></a>


    <script src="{% static 'assets/vendors/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jarallax/jarallax.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-appear/jquery.appear.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-validate/jquery.validate.min.js' %}"></script>
    <script src="{% static 'assets/vendors/nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'assets/vendors/odometer/odometer.min.js' %}"></script>
    <script src="{% static 'assets/vendors/swiper/swiper.min.js' %}"></script>
    <script src="{% static 'assets/vendors/tiny-slider/tiny-slider.min.js' %}"></script>
    <script src="{% static 'assets/vendors/wnumb/wNumb.min.js' %}"></script>
    <script src="{% static 'assets/vendors/wow/wow.js' %}"></script>
    <script src="{% static 'assets/vendors/isotope/isotope.js' %}"></script>
    <script src="{% static 'assets/vendors/countdown/countdown.min.js' %}"></script>
    <script src="{% static 'assets/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendors/twentytwenty/twentytwenty.js' %}"></script>
    <script src="{% static 'assets/vendors/twentytwenty/jquery.event.move.js' %}"></script>
    <script src="{% static 'assets/vendors/bxslider/jquery.bxslider.min.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'assets/vendors/vegas/vegas.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/vendors/timepicker/timePicker.js' %}"></script>


    <script src="http://maps.google.com/maps/api/js?key=AIzaSyATY4Rxc8jNvDpsK8ZetC7JyN4PFVYGCGM"></script>


    <!-- template js -->
    <script src="{% static 'assets/js/izeetak.js' %}"></script>
</body>

</html>

{% endblock content %}

templates/project.html
{% extends "base.html" %}
{% load custom_filters %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Projects || Izeetak || Izeetak HTML Template For IT Solutions Company</title>
    <!-- favicons Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/favicons/apple-touch-icon.png'%}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/favicons/favicon-32x32.png'%}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicons/favicon-16x16.png'%}" />
    <link rel="manifest" href="{% static 'assets/images/favicons/site.webmanifest'%}" />
    <meta name="description" content="Izeetak HTML Template For IT Solutions Company" />

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">


    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/animate/animate.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/animate/custom-animate.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/fontawesome/css/all.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jarallax/jarallax.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/nouislider/nouislider.pips.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/odometer/odometer.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/swiper/swiper.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/izeetak-icons/style.css'%}">
    <link rel="stylesheet" href="{% static 'assets/vendors/tiny-slider/tiny-slider.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/reey-font/stylesheet.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.carousel.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.theme.default.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/twentytwenty/twentytwenty.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/bxslider/jquery.bxslider.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap-select/css/bootstrap-select.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/vegas/vegas.min.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/jquery-ui/jquery-ui.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/vendors/timepicker/timePicker.css'%}" />

    <!-- template styles -->
    <link rel="stylesheet" href="{% static 'assets/css/izeetak.css'%}" />
    <link rel="stylesheet" href="{% static 'assets/css/izeetak-responsive.css'%}" />
</head>

<body>
    <div class="preloader">
        <img class="preloader__image" width="60" src="{% static 'assets/images/loader.png'%}" alt="" /> 
    </div>
    <!-- /.preloader -->
    <div class="page-wrapper">
        <header class="main-header clearfix">
            <div class="main-header__top clearfix">
                <div class="main-header__top-inner clearfix">
                    <div class="main-header__top-left">
                        <ul class="list-unstyled main-header__top-address">
                            <li>
                                <div class="icon">
                                    <span class="icon-pin"></span>
                                </div>
                                <div class="text">
                                    <p>66 Road Broklyn Golden Street. New York</p>
                                </div>
                            </li>
                            <li>
                                <div class="icon">
                                    <span class="icon-email"></span>
                                </div>
                                <div class="text">
                                    <p><a href="mailto:needhelp@company.com">needhelp@company.com</a></p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="main-header__top-right">
                        <div class="main-header__top-right-text">
                            <p><span>Now Hiring:</span> Are you a driven and motivated 1st Line IT Support Engineer?</p>
                        </div>
                        <div class="main-header__top-right-social">
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-facebook"></i></a>
                            <a href="#"><i class="fab fa-pinterest-p"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
        </header>

        <div class="stricky-header stricked-menu main-menu">
            <div class="sticky-header__content"></div><!-- /.sticky-header__content -->
        </div><!-- /.stricky-header -->

        <!--Page Header Start-->
        <section class="page-header">
            <div class="page-header-bg" style="background-image: url({% static 'assets/images/backgrounds/a5.jpg'%})">
            </div>
            <div class="page-header-bg-overly"></div>
            <div class="page-header-shape wow slideInRight" data-wow-delay="100ms" data-wow-duration="2500ms"
                style="background-image: url({% static 'assets/images/shapes/page-header-shape.png'%})"></div>
            <div class="container">
                <div class="page-header__inner">
                    <ul class="thm-breadcrumb list-unstyled">
                        <li><a href="{% url 'it_solution:home' %}">Home</a></li>
                        <li><span>/</span></li>
                        <li>Projects</li>
                    </ul>
                    <h2>Projects</h2>
                </div>
            </div>
        </section>
        <!--Page Header End-->

        <!--Projects Page Start-->
        <section class="project-two project-page">
            <div class="container">
                <div class="row">
                    {% for project in explore_project %}
                   
                    <div class="col-xl-3 col-lg-4 col-md-6 wow fadeInLeft" data-wow-delay="100ms">
                        <!--Project One Single-->

                    <div class="project-one__single">
                        <div class="project-one__img">
                        <img src="{{ project.image.url }}" alt="" style= "height:250px; width:100%; "/>
                        </div>
                        <div class="project-one__content">
                        <p class="project-one__tagline">{{ project.title }}</p>
                        <h2 class="project-one__title">
                            <a href="{% url 'it_solution:project-details' project.id %}">{{ project.description|richtext_truncatewords:10 }}</a>
                        </h2>
                        <div class="project-one__arrow">
                            <a href="{% url 'it_solution:project-details' project.id %}"
                            ><span class="icon-right-arrow"></span
                            ></a>
                        </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        <!--Projects Page End-->

       


    </div><!-- /.page-wrapper -->


    <div class="mobile-nav__wrapper">
        <div class="mobile-nav__overlay mobile-nav__toggler"></div>
        <!-- /.mobile-nav__overlay -->
        <div class="mobile-nav__content">
            <span class="mobile-nav__close mobile-nav__toggler"><i class="fa fa-times"></i></span>

            <div class="logo-box">
                <a href="index.html" aria-label="logo image"><img src="{% static 'assets/images/resources/footer-logo.png'%}"
                        width="155" alt="" /></a>
            </div>
            <!-- /.logo-box -->
            <div class="mobile-nav__container"></div>
            <!-- /.mobile-nav__container -->

            <ul class="mobile-nav__contact list-unstyled">
                <li>
                    <i class="fa fa-envelope"></i>
                    <a href="mailto:needhelp@packageName__.com">needhelp@izeetak.com</a>
                </li>
                <li>
                    <i class="fa fa-phone-alt"></i>
                    <a href="tel:666-888-0000">9802266777</a>
                </li>
            </ul><!-- /.mobile-nav__contact -->
            <div class="mobile-nav__top">
                <div class="mobile-nav__social">
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-facebook-square"></a>
                    <a href="#" class="fab fa-pinterest-p"></a>
                    <a href="#" class="fab fa-instagram"></a>
                </div><!-- /.mobile-nav__social -->
            </div><!-- /.mobile-nav__top -->



        </div>
        <!-- /.mobile-nav__content -->
    </div>
    <!-- /.mobile-nav__wrapper -->

    <div class="search-popup">
        <div class="search-popup__overlay search-toggler"></div>
        <!-- /.search-popup__overlay -->
        <div class="search-popup__content">
            <form action="#">
                <label for="search" class="sr-only">search here</label><!-- /.sr-only -->
                <input type="text" id="search" placeholder="Search Here..." />
                <button type="submit" aria-label="search submit" class="thm-btn">
                    <i class="icon-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <!-- /.search-popup__content -->
    </div>
    <!-- /.search-popup -->

    <a href="#" data-target="html" class="scroll-to-target scroll-to-top"><i class="fa fa-angle-up"></i></a>


    <script src="{% static 'assets/vendors/jquery/jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'assets/vendors/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jarallax/jarallax.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jquery-appear/jquery.appear.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jquery-validate/jquery.validate.min.js'%}"></script>
    <script src="{% static 'assets/vendors/nouislider/nouislider.min.js'%}"></script>
    <script src="{% static 'assets/vendors/odometer/odometer.min.js'%}"></script>
    <script src="{% static 'assets/vendors/swiper/swiper.min.js'%}"></script>
    <script src="{% static 'assets/vendors/tiny-slider/tiny-slider.min.js'%}"></script>
    <script src="{% static 'assets/vendors/wnumb/wNumb.min.js'%}"></script>
    <script src="{% static 'assets/vendors/wow/wow.js'%}"></script>
    <script src="{% static 'assets/vendors/isotope/isotope.js'%}"></script>
    <script src="{% static 'assets/vendors/countdown/countdown.min.js'%}"></script>
    <script src="{% static 'assets/vendors/owl-carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'assets/vendors/twentytwenty/twentytwenty.js'%}"></script>
    <script src="{% static 'assets/vendors/twentytwenty/jquery.event.move.js'%}"></script>
    <script src="{% static 'assets/vendors/bxslider/jquery.bxslider.min.js'%}"></script>
    <script src="{% static 'assets/vendors/bootstrap-select/js/bootstrap-select.min.js'%}"></script>
    <script src="{% static 'assets/vendors/vegas/vegas.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jquery-ui/jquery-ui.js'%}"></script>
    <script src="{% static 'assets/vendors/timepicker/timePicker.js'%}"></script>


    <script src="http://maps.google.com/maps/api/js?key=AIzaSyATY4Rxc8jNvDpsK8ZetC7JyN4PFVYGCGM"></script>


    <!-- template js -->
    <script src="{% static 'assets/js/izeetak.js'%}"></script>
</body>

</html>
{% endblock content %}