it_solution/urls.py
from django.urls import path

from it_solution import views

app_name = 'it_solution'

urlpatterns = [
    path("", views.homeview, name="home"),
    path("about/", views.aboutview, name="about"),
    path("services/", views.servicesview, name="services"),
    path("project/", views.projectview, name="project"),
    path("news/", views.newsview, name="news"),
    path("contact/", views.contactview, name="contact"),
    path("comments/", views.commentview, name="comments"),
    path("cloud-computing/", views.cloudcomputing, name="cloudcomputing"),
    path("it-consultancy/", views.itconsultancy, name="it-consultancy"),
    path("custom-software/", views.customsoftware, name="custom-software"),
    path("news/<int:pk>/", views.newsdetailsview, name="news-details"),
    path("project/<int:pk>/", views.projectdetailsview, name="project-details"),






    path("admin-page/", views.adminview, name= "admin-page"),
    path("addnews/", views.addnewsview, name="addnews"),
    path("newslist/", views.newslistview, name= "newslist"),
    path("addproject/", views.addprojectview, name= "addproject"),
    path("projectlist/", views.projectlistview, name= "projectlist"),

 
    path("editproject/<int:project_id>/", views.editprojectview, name= "editproject"),
    path('delete/<int:project_id>/', views.delete_project, name='delete_project'),
    
    path("editnews/<int:news_id>", views.editnewsview, name= "editnews"),
    path('delete/news/<int:news_id>/', views.delete_news, name='delete_news'),
  
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("it_solution.urls")),
    path("",include("nirajan.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nirajan/urls.py
from django.urls import path

from nirajan import views

app_name = 'nirajan'

urlpatterns = [

    # path('admin_signup/', views.admin_login_view, name='signup'),
    path('login/admin_login/', views.login_view, name='admin_login'),
    path('admin/dashboard/', views.dashboard_view, name='dashboard'),
    path('logout/',views.logout_view, name="logout")
]

templates/admin_pannel/add_news.html
{% extends "admin_pannel/admin_base.html" %} 
{% block page_title%}News {%endblock page_title%} 
{% block page_sub_title%}Add News{%endblock page_sub_title%} 
{% block admin_content%}



<form method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}

    <h1 style="text-align:center;">Add News</h1>
    
    <!-- Image Field -->
    <div class="form-group row">
        <label for="image" class="col-sm-2 col-form-label col-form-label-lg">Image</label>
        <div class="col-sm-10">
            <input type="file" class="form-control form-control-lg" id="image" name="image" placeholder="Upload the image" required>
        </div>
    </div>
    
    <!-- Title Field -->
    <div class="form-group row">
        <label for="title" class="col-sm-2 col-form-label col-form-label-lg">Title</label>
        <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="title" name="title" placeholder="Enter the title" required>
        </div>
    </div>

    <!-- Admin Field -->
    <div class="form-group row">
        <label for="admin" class="col-sm-2 col-form-label col-form-label-lg">Admin</label>
        <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="admin" name="admin" placeholder="Enter the admin" required>
        </div>
    </div>

    <!-- Content Field -->
    <div class="form-group row">
        <label for="content" class="col-sm-2 col-form-label col-form-label-lg">Content</label>
        <div class="col-sm-10">
            <textarea class="form-control form-control-lg" id="content" name="content" placeholder="Enter the content" required></textarea>
        </div>
    </div>

    <!-- Date Field -->
    <div class="form-group row">
        <label for="date" class="col-sm-2 col-form-label col-form-label-lg">Date</label>
        <div class="col-sm-10">
            <input type="date" class="form-control form-control-lg" id="date" name="date" required>
        </div>
    </div>

    <!-- Submit Button -->
    <button type="submit" class="btn btn-primary">Add News</button>
</form>

{% endblock admin_content%}

templates/admin_pannel/add_project.html
{% extends "admin_pannel/admin_base.html" %} 
{% block page_title%}Projects {%endblock page_title%} 
{% block page_sub_title%} Add Project {%endblock page_sub_title%} 
{% block admin_content%}

<form method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}

    <h1 style="text-align:center;">Add Project</h1>

    <div class="form-group row">
        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Image</label>
        <div class="col-sm-10">
          <input type="file" class="form-control form-control-lg" id="image/png" name="image" placeholder="Upload the image">
        </div>
      </div>
      <div class="form-group row">
        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Title</label>
        <div class="col-sm-10">
          <input type="text" class="form-control form-control-lg" id="title" name="title" placeholder="Enter the title">
        </div>
      </div>
    <div class="form-group row">
        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Description</label>
        <div class="col-sm-10">
          <input type="text" class="form-control form-control-lg" id="colFormLabelLg" name="description" placeholder="Enter the Description">
        </div>
    </div>
    <div class="form-group row">
        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Category</label>
        <div class="col-sm-10">
            <select name="category" class="form-control form-control-lg" id="colFormLabelLg" >
                <option value="" selected disabled>--------</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.title }}</option>
                {% endfor %}
    
            </select>
        </div>
    </div>

      <button type="submit" class="btn btn-primary">Add Project </button>
  </form>

{% endblock admin_content%}

templates/admin_pannel/admin_base.html
<!DOCTYPE html>

{% load static  %}

<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<title>IT Solutions Admin</title>
	<!--favicon-->
	<link rel="icon" href="{% static 'assets/images/favicon-32x32.png" type="image/png'%}" />
	<!--plugins-->
	<link href="{% static 'assets/plugins/simplebar/css/simplebar.css'%}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css'%}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/metismenu/css/metisMenu.min.css'%}" rel="stylesheet" />
	<!-- loader-->
	<link href="{% static 'assets/css/pace.min.css'%}" rel="stylesheet" />
	<script src="{% static 'assets/js/pace.min.js'%}"></script>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css'%}" />
	<!-- Icons CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/icons.css'%}" />
	<!-- App CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/app.css'%}" />
	<link rel="stylesheet" href="{% static 'assets/css/dark-sidebar.css'%}" />
	<link rel="stylesheet" href="{% static 'assets/css/dark-theme.css'%}" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
	<!-- wrapper -->
	<div class="wrapper">
		<!--sidebar-wrapper-->
		<div class="sidebar-wrapper" data-simplebar="true">
			<div class="sidebar-header">
				<div class="">
					<img src="{% static 'assets/images/logo-icon.png" class="logo-icon-2'%}" alt="" />
				</div>
				<div class="main-menu-wrapper__logo">
                    <a href="index.html"
                      ><img src="{% static 'assets/images/resources/logo-1.png' %}" alt=""
                    /></a>
                  </div>
				<a href="javascript:;" class="toggle-btn ml-auto"> <i class="bx bx-menu"></i>
				</a>
			</div>
			<!--navigation-->
			<ul class="metismenu" id="menu">
				<li>
					<a href="{% url 'it_solution:admin-page' %}" >
						<div class="parent-icon icon-color-1"><i class="bx bx-home-alt"></i>
						</div>
						<div class="menu-title">Dashboard</div>
					</a>
				</li>
				<li class="menu-label">News</li>
				<li>
					<a href="{% url 'it_solution:addnews' %}">
						<div class="parent-icon icon-color-2"><i class='fas fa-newspaper' style='font-size:24px'></i>
						</div>
						<div class="menu-title"> Add News </div>
					</a>
				</li>
				<li>
					<a href="{% url 'it_solution:newslist' %}">
						<div class="parent-icon icon-color-3"> <i class="fas fa-newspaper"></i>
						</div>
						<div class="menu-title"> News List </div>
					</a>
					
				</li>

				<li class="menu-label">Projects</li>
				<li>
					<a href="{% url 'it_solution:addproject' %}">
						<div class="parent-icon icon-color-9"><i class="bx bx-ghost"></i>
						</div>
						<div class="menu-title">Add Project</div>
					</a>
				</li>

				<li>
					<a  href="{% url 'it_solution:projectlist' %}">
						<div class="parent-icon icon-color-10"><i class="bx bx-spa"></i>
						</div>
						<div class="menu-title">Projects List</div>
					</a>
				</li>
			</ul>
		</div>
					
		<!--end sidebar-wrapper-->
		<!--header-->
		<header class="top-header">
			<nav class="navbar navbar-expand">
				<div class="left-topbar d-flex align-items-center">
					<a href="javascript:;" class="toggle-btn">	<i class="bx bx-menu"></i>
					</a>
				</div>
				<div class="flex-grow-1 search-bar">
					<div class="input-group">
						<div class="input-group-prepend search-arrow-back">
							<button class="btn btn-search-back" type="button"><i class="bx bx-arrow-back"></i>
							</button>
						</div>
						<input type="text" class="form-control" placeholder="search" />
						<div class="input-group-append">
							<button class="btn btn-search" type="button"><i class="lni lni-search-alt"></i>
							</button>
						</div>
					</div>
				</div>
				<div class="right-topbar ml-auto">
					<ul class="navbar-nav">
						<li class="nav-item search-btn-mobile">
							<a class="nav-link position-relative" href="javascript:;">	<i class="bx bx-search vertical-align-middle"></i>
							</a>
						</li>
						
						
						<li class="nav-item dropdown dropdown-user-profile">
							<a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="javascript:;" data-toggle="dropdown">
								<div class="media user-box align-items-center">
									<div class="media-body user-info">
										<p class="user-name mb-0">Nirajan_Sanjyal</p>
										<p class="designattion mb-0">Admin</p>
									</div>
									<img src="{% static 'assets/images//backgrounds/a5.jpg' %}" class="user-img" alt="user avatar">
								</div>
							</a>
							<div class="dropdown-menu dropdown-menu-right">	<a class="dropdown-item" href="javascript:;"><i
										class="bx bx-user"></i><span>Profile</span></a>
								
							
								
								<div class="dropdown-divider mb-0"></div>	<a class="dropdown-item" href="{% url 'nirajan:logout' %}"><i
										class="bx bx-power-off"></i><span>Logout</span></a>
							</div>
						</li>
						<li class="nav-item dropdown dropdown-language">
							<a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="javascript:;" data-toggle="dropdown">
								<div class="lang d-flex">
									<div><img src="{% static 'assets/images/resources/nepal.jpeg' %}" class="user-img" ></i>
									</div>
									<div><span>Nepal</span>
									</div>
								</div>
							</a>
						</li>
					</ul>
				</div>
			</nav>
			
		</header>
		<!--end header-->
		
		<!--page-wrapper-->
		<div class="page-wrapper">
			<!--page-content-wrapper-->
			<div class="page-content-wrapper">
				<div class="page-content">
					<!--breadcrumb-->
					<div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">
						<div class="breadcrumb-title pr-3">{% block page_title%} {%endblock page_title%}</div>
						<div class="pl-3">
							<nav aria-label="breadcrumb">
								<ol class="breadcrumb mb-0 p-0">
									<li class="breadcrumb-item"><a href="javascript:;"><i class='bx bx-home-alt'></i></a>
									</li>
									<li class="breadcrumb-item active" aria-current="page">{% block page_sub_title%} {%endblock page_sub_title%}</li>
								</ol>
							</nav>
						</div>
						{% comment %} <div class="ml-auto">
							<div class="btn-group">
								<button type="button" class="btn btn-primary">Settings</button>
								<button type="button" class="btn btn-primary bg-split-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">	<span class="sr-only">Toggle Dropdown</span>
								</button>
								<div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">	<a class="dropdown-item" href="javascript:;">Action</a>
									<a class="dropdown-item" href="javascript:;">Another action</a>
									<a class="dropdown-item" href="javascript:;">Something else here</a>
									<div class="dropdown-divider"></div>	<a class="dropdown-item" href="javascript:;">Separated link</a>
								</div>
							</div>
						</div> {% endcomment %}
					</div>
					<!--end breadcrumb-->

					{% block admin_content %}
					{% endblock admin_content%}


				</div>
			</div>
		</div>
		<!--end page-wrapper-->
		<!--start overlay-->
		<div class="overlay toggle-btn-mobile"></div>
		<!--end overlay-->
		<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
		<!--End Back To Top Button-->
		<!--footer -->
		<div class="footer">
			<p class="mb-0">Syndash @2020 | Developed By : <a href="https://themeforest.net/user/codervent" target="_blank">codervent</a>
			</p>
		</div>
		<!-- end footer -->
	</div>
	<!-- end wrapper -->
	<!--start switcher-->
	<div class="switcher-wrapper">
		<div class="switcher-btn"> <i class='bx bx-cog bx-spin'></i>
		</div>
		<div class="switcher-body">
			<h5 class="mb-0 text-uppercase">Theme Customizer</h5>
			<hr/>
			<h6 class="mb-0">Theme Styles</h6>
			<hr/>
			<div class="d-flex align-items-center justify-content-between">
				<div class="custom-control custom-radio">
					<input type="radio" id="darkmode" name="customRadio" class="custom-control-input">
					<label class="custom-control-label" for="darkmode">Dark Mode</label>
				</div>
				<div class="custom-control custom-radio">
					<input type="radio" id="lightmode" name="customRadio" checked class="custom-control-input">
					<label class="custom-control-label" for="lightmode">Light Mode</label>
				</div>
			</div>
			<hr/>
			<div class="custom-control custom-switch">
				<input type="checkbox" class="custom-control-input" id="DarkSidebar">
				<label class="custom-control-label" for="DarkSidebar">Dark Sidebar</label>
			</div>
			<hr/>
			<div class="custom-control custom-switch">
				<input type="checkbox" class="custom-control-input" id="ColorLessIcons">
				<label class="custom-control-label" for="ColorLessIcons">Color Less Icons</label>
			</div>
		</div>
	</div>
	<!--end switcher-->
	<!-- JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static 'assets/js/jquery.min.js'%}"></script>
	<script src="{% static 'assets/js/popper.min.js'%}"></script>
	<script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
	<!--plugins-->
	<script src="{% static 'assets/plugins/simplebar/js/simplebar.min.js'%}"></script>
	<script src="{% static 'assets/plugins/metismenu/js/metisMenu.min.js'%}"></script>
	<script src="{% static 'assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js'%}"></script>
	<!-- App JS -->
	<script src="{% static 'assets/js/app.js'%}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	{% block admin_scripts %}
	{% endblock admin_scripts %}
</body>

</html>

templates/admin_pannel/admin_login.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link rel="stylesheet" href="{% static 'assets/css/admin.css' %}"> <!-- Add your CSS file -->
</head>
<body>
    <div class="login-container">
        <h1>Admin Login</h1>
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="alert alert-danger">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</body>
</html> 



{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html> {% endcomment %}

templates/admin_pannel/dashboard.html
{% extends "admin_pannel/admin_base.html" %} 
{% block page_title%}Dashboard {%endblock page_title%} 
{% block page_sub_title%} {%endblock page_sub_title%} 
{% block admin_content%}

<div class="row">
  <div class="col-md-3 text-center">
    <div class="card">
      {% comment %} <img class="card-img-top" src="..." alt="Card image cap" /> {% endcomment %}
      <div class="card-body">
        <h5 class="card-title">Total News</h5>
        <p class="card-text">
          {{ total_news}} 
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 text-center ">
    <div class="card">
      {% comment %} <img class="card-img-top" src="..." alt="Card image cap" /> {% endcomment %}
      <div class="card-body">
        <h5 class="card-title">Total Projects </h5>
        <p class="card-text">
          {{ total_projects }}
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock admin_content%}

templates/admin_pannel/deletenews.html
{% extends "admin_pannel/admin_base.html" %} 
{% load custom_filters %}
{% block page_title%}Delete news{%endblock page_title%} 
{% block page_sub_title%}{%endblock page_sub_title%} 
{% block admin_content%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete News</title>
    <script>
        function confirmDelete(newstitle) {
            if (confirm(`Are you sure you want to delete the project "${newstitle}"? This action cannot be undone.`)) {
                document.getElementById("delete-form").submit();
            }
        }
    </script>
</head>
<body>
    <h1>Delete News</h1>
    <p>Are you sure you want to delete the News "<strong>{{ news.title }}</strong>"?</p>

    <!-- Delete confirmation button -->
    <button onclick="confirmDelete('{{ project.name }}')">Confirm Delete</button>

    <!-- Hidden form to send the delete request -->
    <form id="delete-form" method="post" action="{% url 'it_solution:delete_news' news.id %}">
        {% csrf_token %}
    </form>

    <!-- Cancel button -->
    <a href="{% url 'it_solution:news_list' %}">Cancel</a>
</body>
</html>

{% endblock admin_content%}

templates/admin_pannel/deleteproject.html
{% extends "admin_pannel/admin_base.html" %} 
{% load custom_filters %}
{% block page_title%}Delete Projects{%endblock page_title%} 
{% block page_sub_title%}{%endblock page_sub_title%} 
{% block admin_content%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Project</title>
    <script>
        function confirmDelete(projectName) {
            if (confirm(`Are you sure you want to delete the project "${projectName}"? This action cannot be undone.`)) {
                document.getElementById("delete-form").submit();
            }
        }
    </script>
</head>
<body>
    <h1>Delete Project</h1>
    <p>Are you sure you want to delete the project "<strong>{{ project.name }}</strong>"?</p>

    <!-- Delete confirmation button -->
    <button onclick="confirmDelete('{{ project.name }}')">Confirm Delete</button>

    <!-- Hidden form to send the delete request -->
    <form id="delete-form" method="post" action="{% url 'it_solution:delete_project' project.id %}">
        {% csrf_token %}
    </form>

    <!-- Cancel button -->
    <a href="{% url 'it_solution:project_list' %}">Cancel</a>
</body>
</html>


{% endblock admin_content%}

templates/admin_pannel/editnews.html
{% extends "admin_pannel/admin_base.html" %} 
{% load custom_filters %}
{% block page_title%}Edit News {%endblock page_title%} 
{% block page_sub_title%}  {%endblock page_sub_title%} 
{% block admin_content%}

<form method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}

    <h1 style="text-align:center;">Edit News</h1>
    
    <!-- Image Field -->
    <div class="form-group row">
        <label for="image" class="col-sm-2 col-form-label col-form-label-lg">Image</label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input 
                    type="file" 
                    class="custom-file-input" 
                    id="imageUpload" 
                    name="image" 
                    onchange="showFileName()">
                <label class="custom-file-label" for="imageUpload">{{news.image.url}}</label>
            </div>
        </div>
    </div>
    
    <!-- Title Field -->
    <div class="form-group row">
        <label for="title" class="col-sm-2 col-form-label col-form-label-lg">Title</label>
        <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="title" name="title" placeholder="Enter the title"  value={{ news.title}}  required>
        </div>
    </div>

    <!-- Admin Field -->
    <div class="form-group row">
        <label for="admin" class="col-sm-2 col-form-label col-form-label-lg">Admin</label>
        <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="admin" name="admin" placeholder="Enter the admin"  value={{ news.admin}}   required>
        </div>
    </div>

    <!-- Content Field -->
    <div class="form-group row">
        <label for="content" class="col-sm-2 col-form-label col-form-label-lg">Content</label>
        <div class="col-sm-10">
            <textarea 
            class="form-control form-control-lg" 
            id="contentField" 
            name="content" 
            placeholder="Enter the Description">{{ news.content |striptags }}</textarea>
        
        </div>
    </div>

  

    <!-- Submit Button -->
    <button type="submit" class="btn btn-primary">Edit News</button>
</form>


{% endblock admin_content%}

templates/admin_pannel/news_list.html
{% extends "admin_pannel/admin_base.html" %} 
{% load custom_filters %}
{% block page_title%}News  {%endblock page_title%} 
{% block page_sub_title%} News List {%endblock page_sub_title%} 
{% block admin_content%}

<div class="row">
    {% for news in newslist %}
    <div class="col-md-3 ">
        <div class="card">
            <img src="{{news.image.url}}" class="card-img-top" alt="..." style= "height:250px; width:100%; ">
            <div class="card-body">
            <h5 class="card-title">{{news.title}}</h5>
            <p class="card-text">{{ news.content|richtext_truncatewords:10 }}
            </p>
            <a href="{%url 'it_solution:editnews' news.id %}" class="btn btn-primary">Edit</a>
            <a href="" class="btn btn-primary" style="background-color: red;"  data-toggle="modal" data-target="#exampleModal" data-url="{%url 'it_solution:delete_news' news.id %}">Delete</a>
            </div>
        </div>
    </div>
        {% endfor %}
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete News</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure, you want to delete this News?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a href="" type="button" class="btn btn-primary" id="confirmDeleteButton">Confirm</a>
        </div>
      </div>
    </div>
  </div>


{% endblock admin_content%}

{% block admin_scripts %}
<script>
    // Listen for the modal show event
    $('#exampleModal').on('show.bs.modal', function (event) {
      // Get the button that triggered the modal
      var button = $(event.relatedTarget); 
  
      // Extract the URL from the button's data attribute
      var url = button.data('url'); 
  
      // Update the href of the confirm button in the modal
      var confirmButton = document.getElementById('confirmDeleteButton');
      confirmButton.href = url;
    });
  </script>
{% endblock admin_scripts%}

templates/admin_pannel/project_list.html
{% extends "admin_pannel/admin_base.html" %} 
{% load custom_filters %}
{% block page_title%}Projects {%endblock page_title%} 
{% block page_sub_title%} Project List {%endblock page_sub_title%} 
{% block admin_content%}


<div class="row">
    {% for project in projectlist %}
    <div class="col-md-3 ">
        <div class="card">
            <img src="{{project.image.url}}" class="card-img-top" alt="..." style= "height:250px; width:100%; ">
            <div class="card-body">
            <h5 class="card-title">{{project.title}}.</h5>
            <p class="card-text">{{ project.description|richtext_truncatewords:10 }}
            </p>
            <a href="{%url 'it_solution:editproject' project.id %}" class="btn btn-primary">Edit</a>
            <a href="" class="btn btn-primary" style="background-color: red;"  data-toggle="modal" data-target="#exampleModal" data-url="{%url 'it_solution:delete_project' project.id %}">Delete</a>
            </div>
        </div>
    </div>
        {% endfor %}
</div>

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Project</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure, you want to delete this?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a href="" type="button" class="btn btn-primary" id="confirmDeleteButton">Confirm</a>
        </div>
      </div>
    </div>
  </div>


{% endblock admin_content%}

{% block admin_scripts %}
<script>
    // Listen for the modal show event
    $('#exampleModal').on('show.bs.modal', function (event) {
      // Get the button that triggered the modal
      var button = $(event.relatedTarget); 
  
      // Extract the URL from the button's data attribute
      var url = button.data('url'); 
  
      // Update the href of the confirm button in the modal
      var confirmButton = document.getElementById('confirmDeleteButton');
      confirmButton.href = url;
    });
  </script>
{% endblock admin_scripts%}